/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class along_chen_com_chenlong_JNI */

#ifndef _Included_along_chen_com_chenlong_JNI
#define _Included_along_chen_com_chenlong_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     along_chen_com_chenlong_JNI
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_along_chen_com_chenlong_JNI_helloWorld
  (JNIEnv *, jobject);

/*
 * Class:     along_chen_com_chenlong_JNI
 * Method:    callBackJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_along_chen_com_chenlong_JNI_callBackJava
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
